services:
  - type: web
    runtime: python
    name: job-description-matcher
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: streamlit run app.py
